services:
  sec2-db:
    image: postgres:latest
    container_name: sec2-group-db
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "${DATABASE_PORT}:5432"
  sec2-app:
    image: prawee/strapi:latest
    container_name: sec2-group-app
    environment:
      DATABASE_CLIENT: ${APP_DB_CLIENT}
      DATABASE_NAME: ${APP_DB_NAME}
      DATABASE_HOST: ${APP_DB_HOST}
      DATABASE_PORT: ${APP_DB_PORT}
      DATABASE_USERNAME: ${APP_DB_USER}
      DATABASE_PASSWORD: ${APP_DB_PASS}
    ports:
      - "${APP_PORT}:${APP_STRAPI_PORT}"